const {get} = require('lodash');

module.exports.tick = (candle) => ({
  timestamp: candle.timestamp,
  product: candle.product,
  open: candle.open,
  close: candle.close,
  high: candle.high,
  low: candle.low,
  last: candle.price,
  color: candle.color,
  closed: candle.closed,
  height: candle.height,
  spread: candle.spread,
  volume: candle.volume,
  sma_10: get(candle, 'sma[\'10\']', null),
  sma_20: get(candle, 'sma[\'20\']', null),
  sma_50: get(candle, 'sma[\'50\']', null),
  sma_100: get(candle, 'sma[\'100\']', null),
  sma_200: get(candle, 'sma[\'200\']', null),
  sma_500: get(candle, 'sma[\'500\']', null),
  sma_1000: get(candle, 'sma[\'1000\']', null),
  ema_10: get(candle, 'ema[\'10\']', null),
  ema_20: get(candle, 'ema[\'20\']', null),
  ema_50: get(candle, 'ema[\'50\']', null),
  ema_100: get(candle, 'ema[\'100\']', null),
  ema_200: get(candle, 'ema[\'200\']', null),
  ema_500: get(candle, 'ema[\'500\']', null),
  ema_1000: get(candle, 'ema[\'1000\']', null),
  regression_10_slope: get(candle, 'regression[\'10\'].slope', null),
  regression_10_intercept: get(candle, 'regression[\'10\'].intercept', null),
  regression_10_r2: get(candle, 'regression[\'10\'].r2', null),
  regression_20_slope: get(candle, 'regression[\'20\'].slope', null),
  regression_20_intercept: get(candle, 'regression[\'20\'].intercept', null),
  regression_20_r2: get(candle, 'regression[\'20\'].r2', null),
  regression_50_slope: get(candle, 'regression[\'50\'].slope', null),
  regression_50_intercept: get(candle, 'regression[\'50\'].intercept', null),
  regression_50_r2: get(candle, 'regression[\'50\'].r2', null),
  regression_100_slope: get(candle, 'regression[\'100\'].slope', null),
  regression_100_intercept: get(candle, 'regression[\'100\'].intercept', null),
  regression_100_r2: get(candle, 'regression[\'100\'].r2', null),
  regression_200_slope: get(candle, 'regression[\'200\'].slope', null),
  regression_200_intercept: get(candle, 'regression[\'200\'].intercept', null),
  regression_200_r2: get(candle, 'regression[\'200\'].r2', null),
  regression_500_slope: get(candle, 'regression[\'500\'].slope', null),
  regression_500_intercept: get(candle, 'regression[\'500\'].intercept', null),
  regression_500_r2: get(candle, 'regression[\'500\'].r2', null),
  regression_1000_slope: get(candle, 'regression[\'1000\'].slope', null),
  regression_1000_intercept: get(candle, 'regression[\'1000\'].intercept', null),
  regression_1000_r2: get(candle, 'regression[\'1000\'].r2', null)
});
