const Sequelize = require('sequelize');

module.exports = {
  tick: {
    timestamp: Sequelize.DATE,
    product: Sequelize.STRING,
    open: Sequelize.REAL,
    close: Sequelize.REAL,
    high: Sequelize.REAL,
    low: Sequelize.REAL,
    last: Sequelize.REAL,
    closed: Sequelize.BOOLEAN,
    height: Sequelize.REAL,
    spread: Sequelize.REAL,
    volume: Sequelize.REAL,
    color: Sequelize.STRING,
    sma_10: Sequelize.REAL,
    sma_20: Sequelize.REAL,
    sma_50: Sequelize.REAL,
    sma_100: Sequelize.REAL,
    sma_200: Sequelize.REAL,
    sma_500: Sequelize.REAL,
    sma_1000: Sequelize.REAL,
    ema_10: Sequelize.REAL,
    ema_20: Sequelize.REAL,
    ema_50: Sequelize.REAL,
    ema_100: Sequelize.REAL,
    ema_200: Sequelize.REAL,
    ema_500: Sequelize.REAL,
    ema_1000: Sequelize.REAL,
    regression_10_slope: Sequelize.REAL,
    regression_10_intercept: Sequelize.REAL,
    regression_10_r2: Sequelize.REAL,
    regression_20_slope: Sequelize.REAL,
    regression_20_intercept: Sequelize.REAL,
    regression_20_r2: Sequelize.REAL,
    regression_50_slope: Sequelize.REAL,
    regression_50_intercept: Sequelize.REAL,
    regression_50_r2: Sequelize.REAL,
    regression_100_slope: Sequelize.REAL,
    regression_100_intercept: Sequelize.REAL,
    regression_100_r2: Sequelize.REAL,
    regression_200_slope: Sequelize.REAL,
    regression_200_intercept: Sequelize.REAL,
    regression_200_r2: Sequelize.REAL,
    regression_500_slope: Sequelize.REAL,
    regression_500_intercept: Sequelize.REAL,
    regression_500_r2: Sequelize.REAL,
    regression_1000_slope: Sequelize.REAL,
    regression_1000_intercept: Sequelize.REAL,
    regression_1000_r2: Sequelize.REAL,
  }
}
